# Generated by Django 3.0.3 on 2020-02-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
